<?php
/**
 * PluginSettingsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package     uSettingsDoctrinePlugin
 * @subpackage  task
 * @author      Henning Glatter-Gotz <henning@glatter-gotz.com>
 */
class PluginSettingsTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginSettingsTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginSettings');
  }

  public function getByKeyGroup($key, $group)
  {
    $q = $this->createQuery('s')
        ->where('s.key = ?', $key)
        ->andWhere('s.group = ?', $group);

    $r = $q->execute();

    if ($r->count() === 1)
    {
      $r = $r->getFirst();
    }
    else if ($r->count() === 0)
    {
      $r = null;
    }
    else
    {
      throw new Exception(__METHOD__.':'.__LINE__.
        '|Expected one result but found '.$r->count());
    }

    return $r;
  }

  public function setByKeyGroup($key, $value, $group)
  {
    $kv = self::getByKeyGroup($key, $group);

    if (null === $kv)
    {
      throw new Exception('The configuration setting with key \''.$key.
          '\' and group \''.$group.'\' does not exist.');
    }

    $kv->setValue($value);
    $kv->save();
  }

  public function getAllGroup($group)
  {
    $q = $this->createQuery('s')
        ->where('s.group = ?', $group);

    $r = $q->execute();

    return $r;
  }

  public function newSetting($key, $value, $type, $group)
  {
    $kv = self::getByKeyGroup($key, $group);

    if (null !== $kv)
    {
      throw new Exception('Key \''.$key.'\' already exists.');
    }

    $nKv = new Settings();
    $nKv->setKey($key);
    $nKv->setValue($value);
    $nKv->setType($type);
    $nKv->setGroup($group);
    $nKv->save();
  }

  public function removeByGroup($group)
  {
    $q = $this->createQuery()
        ->delete('settings s')
        ->where('s.group = ?', $group);

    $q->execute();
  }

  public function removeByKeyGroup($key, $group)
  {
    $q = $this->createQuery()
        ->delete('settings s')
        ->where('s.key = ?', $key)
        ->andWhere('s.group = ?', $group);

    $q->execute();
  }

  public function optimize()
  {
    $sql = "OPTIMIZE TABLE `settings`;";
    Doctrine_Manager::getInstance()->getConnectionForComponent('PluginSettings')->getDbh()->query($sql);
  }
}