<?php
/**
 * PluginSettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package     uSettingsDoctrinePlugin
 * @subpackage  task
 * @author      Henning Glatter-Gotz <henning@glatter-gotz.com>
 */
abstract class PluginSettings extends BaseSettings
{
}